version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123123
      - DB_NAME=fraud_detection
      - DB_PORT=3306
      - OPENAI_API_KEY=ck-nguyen.tien.data-QulbvcPGIWerFxcgQbJH8XH2lYlT
      - OPENAI_BASE_URL=https://openai-proxy-apigw-genai.api.linecorp.com/v1
      - OPENAI_MODEL=gpt-4o
      - ABUSEIPDB_API_KEY=1399a3fb0b5e1896e61a917c31aa501cdde1401ad36c5b1a81c8120dde11e9e7be5e139cac6904f8
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: fraud_detection
    volumes:
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
      - ./docker/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
